# Ime pipeline-a za backend
name: Backend CI

# Dogodki, ki sprožijo workflow (push in pull request na glavno vejo)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  
      uses: actions/checkout@v3

    - name: Setup Node.js  
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache node_modules 
      uses: actions/cache@v3
      with:
        path: rirs-backend/node_modules  # Pot do mape node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('rirs-backend/package-lock.json') }}  # Ključ za cache
        restore-keys: |
          ${{ runner.os }}-backend-
      # ⚠️ Caching:
      # - Če cache obstaja (cache hit), se node_modules obnovi, preden se zažene npm install.
      # - Če cache ne obstaja (cache miss), npm install ponovno ustvari mapo node_modules.

    - name: Install dependencies  # Namestitev odvisnosti
      run: |
        cd rirs-backend
        npm ci

    - name: Upload backend artifacts  # Naložitev artefaktov za backend
      uses: actions/upload-artifact@v4
      with:
        name: backend-build  # Ime artefakta
        path: |
          rirs-backend/  
          rirs-backend/node_modules/  
        # Pot do celotne kode
        # Nameščene odvisnosti

  # Job za testiranje backenda
  test-backend:
    needs: build-backend 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3

    - name: Setup Node.js  
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache node_modules  
      uses: actions/cache@v3
      with:
        path: backend/node_modules  
        key: ${{ runner.os }}-backend-${{ hashFiles('rirs-backend/package-lock.json') }}  # Ključ za cache
        restore-keys: |
          ${{ runner.os }}-backend-

    - name: Install dependencies  # Namestitev odvisnosti
      run: |
        cd rirs-backend
        npm install

    - name: Run tests with coverage  # Izvajanje testov s pokritostjo
      run: |
        cd rirs-backend
        npm run test:ci

    - name: Upload coverage report  # Naložitev poročila o pokritosti kode
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage  # Ime artefakta
        path: rirs-backend/coverage/  # Pot do poročila o pokritosti kode